# permissions for end users to edit networkloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkloadbalancer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pomidor
    app.kubernetes.io/part-of: pomidor
    app.kubernetes.io/managed-by: kustomize
  name: networkloadbalancer-editor-role
rules:
- apiGroups:
  - aws.pomidor
  resources:
  - networkloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.pomidor
  resources:
  - networkloadbalancers/status
  verbs:
  - get
