apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "${ROLE_ARN}"
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pomidor
    app.kubernetes.io/part-of: pomidor
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
